#!/bin/bash
#
# Run all the libutf8 tests with coverage
#
# Copyright:    Copyright (c) 2011-2019  Made to Order Software Corp.  All Rights Reserved
#
# https://snapwebsites.org/project/libutf8
# contact@m2osw.com
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.
#

set -e

if test "$1" = "--help" -o "$1" = "-h"
then
    echo "Usage: $0 [--opt]"
    echo "where --opt is one of:"
    echo "   --help | -h    display this help screen"
    exit 1;
fi

TEST_NAME=
if test -n "$1"
then
    TEST_NAME="$1"
fi


start_date=`date`
SOURCE=`pwd`
VERSION=`dpkg-parsechangelog --show-field Version | sed -e 's/~.*//' -e 's/\(^[0-9]\+\.[0-9]\+\.[0-9]\+\).*/\1/'`
echo "***"
echo "*** libutf8 coverage for version $VERSION ($start_date)"
echo "***"
mkdir -p tmp/coverage
rm -rf tmp/coverage/*
cd tmp/coverage
mkdir BUILD
cd BUILD
# request coverage in this build
dist=`cd ../../../../../../; pwd`/BUILD/dist
modules=$dist/share/cmake-3.5/Modules
cmake -DCMAKE_INSTALL_PREFIX:PATH=$dist \
    -DCMAKE_MODULE_PATH:PATH=$modules \
    -DCMAKE_BUILD_TYPE=Debug \
    -Dutf8_library_COVERAGE:BOOL=ON \
    ../../..
cd ..
echo
echo "***"
echo "*** compile (`date`)"
echo "***"
VERBOSE=1 make -j 8 -C BUILD
echo
echo "***"
echo "*** run (`date`)"
echo "***"
if test `BUILD/tests/unittest --version` != "$VERSION"
then
    echo "the version of unittest (`BUILD/tests/unittest --version`) is not equal to the project version ($VERSION)"
    exit 1;
fi

# We test the pipe status on exit to detect whether the test failed
echo "Start running the tests on `date`" >test_log.txt
echo >>test_log.txt
BUILD/tests/unittest "${TEST_NAME}" --progress 2>&1 | tee -a test_log.txt; test ${PIPESTATUS[0]} -eq 0
echo >>test_log.txt
echo "Finished running the tests on `date`" >>test_log.txt
echo
echo "***"
echo "*** gcov/lcov (`date`)"
echo "***"

# Choose one of the following gcov commands
mkdir -p gcov
cd gcov
gcov -o ../BUILD/src/CMakeFiles/libutf8.dir/libutf8.cpp.gcno ../../../src/libutf8.cpp
cd ..


#lcov --capture --directory BUILD --output-file coverage.info
# The following lcov options can be used under Ubuntu 14.04+
# Use --no-external and --base-directory $SOURCE
# to avoid /usr/include and other unwanted files
# (only available in lcov version 1.10+)
lcov --capture --no-external --directory BUILD --base-directory $SOURCE --output-file coverage.info
mkdir -p html
genhtml --legend --demangle-cpp --no-branch-coverage --show-details coverage.info --output-directory html


end_date=`date`

# Statistics
echo "<html><head><title>libutf8 $VERSION statistics</title></head><body>" >html/statistics.html
echo "<h3>Statistics of the libutf8 $VERSION library</h3><pre>" >>html/statistics.html
cloc $SOURCE/libutf8/ >>html/statistics.html
echo "</pre><h3>Statistics of the libutf8 $VERSION tests</h3><pre>" >>html/statistics.html
cloc $SOURCE/tests/ >>html/statistics.html
#echo "</pre><h3>Statistics of libutf8 tools $VERSION</h3><pre>" >>html/statistics.html
#cloc $SOURCE/tools/ >>html/statistics.html
echo "</pre></body></html>" >>html/statistics.html

# Test output (Logs)
echo "<html><head><title>libutf8 $VERSION test logs</title></head><body><h3>Logs for the libutf8 $VERSION tests</h3><p>Tests started on $start_date and finished on $end_date</p><pre>" >html/test_log.html
if test -f test_log.txt
then
    # If test_log.txt does not exist, the user got the logs in the
    # console already
    cat test_log.txt >>html/test_log.html
fi
echo "</pre></body></html>" >>html/test_log.html


# For publication, if that directory does not exist, you probably don't
# have a website to display this data
PUBLISH_DIR=/usr/clients/www/lcov.snapwebsites.org/public_html
if test -z "${TEST_NAME}" -a -d ${PUBLISH_DIR}
then
    echo "***"
    echo "*** publication to lcov.snapwebsites.org ($end_date)"
    echo "***"

    # Create folder for this specific version
    mkdir -p ${PUBLISH_DIR}/libutf8/libutf8-$VERSION

    # Make sure we have the latest index
    cp $SOURCE/dev/index.php ${PUBLISH_DIR}/libutf8

    # Copy coverage and statistics HTML results
    cp -r html/* ${PUBLISH_DIR}/libutf8/libutf8-$VERSION/.
fi

echo "Process started  on $start_date"
echo "Process finished on $end_date"

# vim: ts=4 sw=4 et
